updates CI v13

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -175,29 +175,14 @@ jobs:
         echo "::notice title=Commit::${{needs.test.outputs.commit}}"
 
         RES=$(curl -X POST \
+          --fail-with-body \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           https://api.github.com/repos/${{ github.repository }}/actions/workflows/dockerize.yml/dispatches \
           -d '{"ref":"${{ github.ref }}", "inputs": {"git_reference": "${{ needs.test.outputs.commit }}", "tag": "${{ github.ref_name }}"}')
-
-         echo "::notice:: API call to 'dockerize.yml' response! $RES"
-
-#        CURL_EXIT_CODE=$?
-#        if [[ $CURL_EXIT_CODE -ne 0 ]]; then
-#          printf "::error::cURL failed %d.\nOutput cURL: %s\n" "$CURL_EXIT_CODE" "$RES"
-#          exit 1
-#        fi
-#
-#        STATUS=$(echo "$RES" | jq -r '.status // "N/A"')
-#        MESSAGE=$(echo "$RES" | jq -r '.message // "No message provided."')
-#
-#        if [[ "$STATUS" == "N/A" && "$RES" != "" ]]; then
-#          printf "::error::Error: Uknown response.\nResponse is: %s\n" "$RES"
-#          exit 1
-#        fi
-#        if [[ "$STATUS" == "200" || "$STATUS" == "201" || "$STATUS" == "204" ]]; then
-#            echo "::notice:: API call to 'dockerize.yml' successed! Status: $STATUS"
-#        else
-#            printf "::error::Error: API call to 'dockerize.yml' failed with status %s.\nMessage: %s\n" "$STATUS" "$MESSAGE"
-#            exit 1
-#        fi
+        CURL_EXIT_CODE=$?
+        if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+          printf "::error::cURL failed %d.\nOutput cURL: %s\n" "$CURL_EXIT_CODE" "$RES"
+          exit 1
+        fi
+        echo "::notice:: API call to 'dockerize.yml' succesed"
