enable deployment pipeline

diff --git a/.github/workflows/trigger-azure-pipeline.yml b/.github/workflows/trigger-azure-pipeline.yml
--- a/.github/workflows/trigger-azure-pipeline.yml
+++ b/.github/workflows/trigger-azure-pipeline.yml
@@ -26,28 +26,28 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # - name: Trigger deploy
-      #   run: |
-      #     pipelineId=${{ inputs.azure-pipeline-id }}
+      - name: Trigger deploy
+        run: |
+          pipelineId=${{ inputs.azure-pipeline-id }}
 
-      #     IFS=',' read -ra pipelines <<< "$pipelineId"
-      #     for pipeline in "${pipelines[@]}"; do
-      #       jsonBody='{"variables": {"sha": {"isSecret": false, "value": "${{ github.sha }}"}, "tag": {"isSecret": false, "value": "${{ inputs.image-tag }}"}}}'
-      #       contentLength=$(echo -n $jsonBody | wc -c)
-      #       organization=${{ inputs.azure-organization }}
-      #       project=${{ inputs.azure-project }}
+          IFS=',' read -ra pipelines <<< "$pipelineId"
+          for pipeline in "${pipelines[@]}"; do
+            jsonBody='{"variables": {"sha": {"isSecret": false, "value": "${{ github.sha }}"}, "tag": {"isSecret": false, "value": "${{ inputs.image-tag }}"}}}'
+            contentLength=$(echo -n $jsonBody | wc -c)
+            organization=${{ inputs.azure-organization }}
+            project=${{ inputs.azure-project }}
 
-      #       echo Triggering deploy for pipeline $pipeline
-      #       echo JSON body: $jsonBody
+            echo Triggering deploy for pipeline $pipeline
+            echo JSON body: $jsonBody
 
-      #       curl -f -v -L \
-      #         -u ":${{ secrets.azure-pat }}" \
-      #         -H "Content-Type: application/json" \
-      #         -H "Content-Length: $contentLength" \
-      #         -d "$jsonBody" \
-      #         https://dev.azure.com/$organization/$project/_apis/pipelines/$pipeline/runs?api-version=7.1-preview.1
-      #       if [ $? -ne 0 ]; then
-      #         echo "Failed to trigger deploy for pipeline $pipeline"
-      #         exit 1
-      #       fi
-      #     done
+            curl -f -v -L \
+              -u ":${{ secrets.azure-pat }}" \
+              -H "Content-Type: application/json" \
+              -H "Content-Length: $contentLength" \
+              -d "$jsonBody" \
+              https://dev.azure.com/$organization/$project/_apis/pipelines/$pipeline/runs?api-version=7.1-preview.1
+            if [ $? -ne 0 ]; then
+              echo "Failed to trigger deploy for pipeline $pipeline"
+              exit 1
+            fi
+          done
